"""actualizacion de tabla registroTarea

Revision ID: 126fca0c0fbd
Revises: 848553608089
Create Date: 2024-03-11 16:25:25.310074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126fca0c0fbd'
down_revision = '848553608089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recordar', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_tareas', schema=None) as batch_op:
        batch_op.drop_column('recordar')

    # ### end Alembic commands ###
