"""actualizacion de tabla registroTarea

Revision ID: ec426f869334
Revises: 2e1abf9ef54f
Create Date: 2024-03-11 17:29:23.045128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec426f869334'
down_revision = '2e1abf9ef54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.alter_column('recordar',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Interval(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_tareas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('recordar',
               existing_type=sa.Interval(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
